version: '3.0'
services:
   nginx:
    image: nginx:latest
    container_name: dollarcontainer
    ports:
      - 80:80
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
